
services:
  nginx:
    build: .
    container_name: stamp-management-nginx
    ports:
      - "${PORT:-8090}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/web:/web
